### ISSUE TITLE
I don't understand how to declare "context"

### ISSUE THREAD

**Issue by MetaSpl0day** [apsun/RemotePreferences#11]
Hello,
I follow your guide to use RemotePreferences : my goal is to change a text color of Samsung Music, and I use your library to allow me to get the value returned by a colorpicker.

I succeed with SharedPreferences library to save my value and to recover them when I open my app, but now I don't arrived to recover this value with your library in my Module.java

I know it's not a bug but I don't understand by what I can declare your "context" variable.
 ```
 SharedPreferences prefs = new RemotePreferences(context, "com.chacha.samsungmusiccustomiser", "main_prefs");
        value = prefs.getInt("MiniArtistColor", 0); 
```

I use this in my Module.java
Can you help me please ?
I'm sorry if there are mistakes I'm french

**Comment by apsun** [comment]
Are you using Xposed (or something similar)? Generally you would get the context value from the thing you are hooking as a parameter or field. Since you're touching the UI, there is basically always a context field you can get from somewhere nearby. I have also heard that https://stackoverflow.com/a/12495865 works, but I strongly recommend against it as it's an implementation detail of the system.

**Comment by MetaSpl0day** [comment]
Thanks for you reply Apsun it's nice :) Yes I use more precisely EdXposed but it use same synthax and libraries. 

Ok thanks for the info (I will try the solution of your link tomorrow it's 00:33am here 😅)

And to get the context of the Activity I hook how can I do this if you can help me ? I searched and tried a lot of differents solutions and I don't arrived to make it working.

If you need my Module code or other I can no problem :)

Thanks you,
Have nice day
