### ISSUE TITLE
[Question] RemotePreferences not loaded after Android reboot

### ISSUE THREAD

**Issue by hvdwolf** [apsun/RemotePreferences#4]
Hi,

I just applied your RemotePreference library to an Xposed module which needed to be adapted for Android 8.0.0.
After some trial and error it works fine, but for one thing: After an Android reboot it doesn't load the Preferences correctly in the part of the xposed module that should act on the settings. 
I have to go into the Settings (gui part of SettingsFragment) again, "do something" and then it is OK again.

My  github is here: https://github.com/hvdwolf/XSofiaTweaker
The only things actually important are the [Settingsfragment.java](https://github.com/hvdwolf/XSofiaTweaker/blob/master/app/src/main/java/org/hvdw/xsofiatweaker/SettingsFragment.java) and the [XSofiaTweaker.java](https://github.com/hvdwolf/XSofiaTweaker/blob/master/app/src/main/java/org/hvdw/xsofiatweaker/XSofiaTweaker.java).

I'm a beginning java and beginning xposed programmer so I already assume I did something incorrect.
Note that the code still contains a lot of non-functional crap as I simply don't know how to get it working, but that is not my question.

**Comment by apsun** [comment]
Can you try enabling strict mode (see the readme) and attach a logcat? Thanks.

Also not sure how well RemotePreferences plays with file permissions. You shouldn't need to chmod (`setReadable`) the preference xml files for the library to work. Try removing that code and see if it helps.

**Comment by hvdwolf** [comment]
Thanks for your quick response. I will work on it and give feedback.

**Edit:** I removed the setReadable actions and also without the strict mode it works really fine.
Preferences are updated immediately and accessible, also after a full reboot.

Thanks a lot. Also for your excellent library.

**Edit 2:** I don't seem to be able to close the issue.

**Comment by apsun** [comment]
Good to hear! Glad it's working now :-)

**Comment by Rijul-A** [comment]
Hi there, I faced this problem too. Reading preference keys and values **at boot** from hooks in system apps is not possible, until the system is unlocked. This is expected behaviour due to [Android N's Direct Boot mode](https://blog.stylingandroid.com/nougat-direct-boot/) which encrypts everything (file-based encryption, including the preference xml file) and prevents any apps from using internal storage. It blocks ContentProviders too, as used in RemotePreferences. Reproducing this issue in hooked user apps is tough, because most of them load only after unlock.

The workaround for this (found in [GravityBox](https://github.com/GravityBox/GravityBox/commit/d825b7be445c18de9a90eb8f77c1c5eb2b74deb8)) is to use Device Protected Storage (as opposed to Credential Protected Storage), through `context = context.createDeviceProtectedStorageContext();` wherever needed. This must be done in 
- Xposed (before using your constructor for RemotePreferences), and 
- A few locations in RemotePreferences itself (#5), because the default context is the Credential Protected Storage context
- The app's preferences, either through [preferenceManager.setStorageDeviceProtected()](https://developer.android.com/reference/android/preference/PreferenceManager#setStorageDeviceProtected()), or through overriding the getSharedPreferences in your activity to use the correct context.

This also links back to my old issue #2, where I couldn't figure out what was going in earlier. Hope this helps someone.
