### ISSUE TITLE
Should checkAccess check for the preferences owner package?

### ISSUE THREAD

**Issue by rraallvv** [apsun/RemotePreferences#8]
Maybe I'm missing something obvious, but should I check whether the calling package is the preferences owner in `checkAccess()` in the `RemotePreferenceProvider` subclass to give it write access, or is write access automatically granted to the preferences owner even when `checkAccess()` always return `false`. Also, what are should I use to call `getCallingPackage()` from API 17, since that method is not available on that API. Keep the good work.

**Comment by apsun** [comment]
It does exactly what it says on the tin, if you return `true` the access is permitted, if you return `false` it's rejected. This applies even if you are calling it from within the app that owns the preferences; however you should not be doing that anyways, if you own the preferences then you can just directly use `SharedPrefences` to access them.

I'm not sure what you mean by `getCallingPackage` not being available; the docs say it was there since 1.0.

**Comment by rraallvv** [comment]
Thanks for looking into this, I was able to give write access to the preferences owner via the `SharedPreferences` as you said, the problem is that I was trying to use `RemotePreferences` from a library that is meant to be used from both the preferences owner and also other apps. `getCallingPacked` was added to `ContentProvider` in [API 19](https://developer.android.com/reference/android/content/ContentProvider.html#getCallingPackage)

**Comment by apsun** [comment]
Ah my bad, I was looking at `Activity.getCallingPackage`. Honestly I have no idea; personally I would recommend against using `getCallingPackage` altogether. If you are just storing ordinary preferences (no passwords/tokens) there is probably nothing wrong with just letting anyone read them. If you have sensitive preferences but don't need to remotely access them, split your preferences into a private and a public file, and only pass the public one to the provider constructor.

If you really want to limit it to one app or you need write permissions, you might be able to use `Binder.getCallingUid`, which is available since API1.

**Comment by rraallvv** [comment]
Thanks.
